# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mttu6gHr1xyUPycOtsYHFYIM4bvB5tnM
"""

# ============================
# 1. Upload do CSV para o Colab
# ============================
from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Upload do arquivo Walmart.csv
uploaded = files.upload()
csv_file = list(uploaded.keys())[0]

# ============================
# 2. Carregar e explorar o dataset
# ============================
df = pd.read_csv(csv_file)

print("Informações do dataset:")
print(df.info())

print("\nEstatísticas descritivas:")
print(df.describe())

print("\nValores nulos:")
print(df.isnull().sum())

# ============================
# 3. Análises
# ============================
# Vendas por loja
sales_by_store = df.groupby("Store")["Weekly_Sales"].sum().sort_values(ascending=False)
print("\nVendas totais por loja:")
print(sales_by_store)

# Top 5 lojas
top_stores = sales_by_store.head(5)
print("\nTop 5 lojas com maior faturamento:")
print(top_stores)

# Loja que mais vendeu
print("\nLoja que mais vendeu:")
print(top_stores.head(1))

# Semana com mais vendas (se houver coluna 'Date')
if "Date" in df.columns:
    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
    max_week = df.loc[df['Weekly_Sales'].idxmax()]
    print("\nSemana com mais vendas:")
    print(max_week)

# ============================
# 4. Visualizações + Salvando
# ============================
from google.colab import files

# Gráfico 1 - Vendas semanais ao longo do tempo
if "Date" in df.columns:
    plt.figure(figsize=(12,6))
    plt.plot(df['Date'], df['Weekly_Sales'])
    plt.title("Vendas Semanais ao longo do tempo")
    plt.xlabel("Data")
    plt.ylabel("Vendas")
    plt.grid(True)
    plt.savefig("grafico_vendas_tempo.png")  # salva no Colab
    plt.show()

# Gráfico 2 - Vendas totais por loja
plt.figure(figsize=(12,6))
sns.barplot(x=sales_by_store.index, y=sales_by_store.values, palette="viridis")
plt.title("Vendas Totais por Loja")
plt.xlabel("Loja")
plt.ylabel("Total de Vendas")
plt.savefig("grafico_vendas_lojas.png")  # salva no Colab
plt.show()

# ============================
# 5. Download automático dos gráficos
# ============================
files.download("grafico_vendas_tempo.png")
files.download("grafico_vendas_lojas.png")